<?php
/**
 * The file that defines the Service Landing Page custom fields
 *
 * @link       https://github.com/AgriLife/af4-agrilife-unit/blob/master/fields/service-landing-page-fields.php
 * @since      1.5.0
 * @package    af4-agrilife-unit
 * @subpackage af4-agrilife-unit/fields
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6c1bb37abe5cb',
			'title'                 => 'Service Landing Page',
			'fields'                => array(
				array(
					'key'               => 'field_6c8fbfba2f80c',
					'label'             => 'Heading',
					'name'              => 'heading_group',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6c8fa0d6f1bee',
							'label'             => 'Show Page Title',
							'name'              => 'show_page_title',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 1,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
					),
				),
				array(
					'key'               => 'field_6c82929dc35e1',
					'label'             => 'Sections',
					'name'              => 'sections',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'layout_5c82aea80f659' => array(
							'key'        => 'layout_5c82aea80f659',
							'name'       => 'item_section',
							'label'      => 'Items',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_6c8297e1c35eb',
									'label'             => 'Title',
									'name'              => 'title',
									'type'              => 'group',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'layout'            => 'block',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6c8297e1c35ec',
											'label'        => 'Text',
											'name'         => 'text',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_6c8297e1c35ed',
											'label'        => 'Underline Color',
											'name'         => 'underline_color',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'field_6c8297e1c35ec',
														'operator' => '!=empty',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'none' => 'None',
												'lightgreen' => 'Light Green',
												'lightblue' => 'Light Blue',
											),
											'default_value' => array(
												0 => 'lightgreen',
											),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
									),
								),
								array(
									'key'               => 'field_6c8297e1c35ee',
									'label'             => 'Background Color',
									'name'              => 'background_color',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'none'     => 'None',
										'darkblue' => 'Dark Blue',
									),
									'default_value'     => array(
										0 => 'none',
									),
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'ajax'              => 0,
									'return_format'     => 'value',
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_6c8297e1c35ef',
									'label'             => 'Columns',
									'name'              => 'columns',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										2 => '2',
										3 => '3',
										4 => '4',
									),
									'default_value'     => array(
										0 => 4,
									),
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'ajax'              => 0,
									'return_format'     => 'value',
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_6c87c85f43675',
									'label'             => 'Items',
									'name'              => 'items_group',
									'type'              => 'group',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'layout'            => 'block',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6c87c8da43676',
											'label'        => 'Alignment',
											'name'         => 'align',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'left'   => 'Left',
												'center' => 'Center',
												'right'  => 'Right',
											),
											'default_value' => array(
												0 => 'center',
											),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_6c87ce476762d',
											'label'        => 'Type',
											'name'         => 'type',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'card' => 'Card',
												'flowchart' => 'Flowchart',
											),
											'default_value' => array(
												0 => 'cards',
											),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_6c1bb3d180cc2',
											'label'        => '',
											'name'         => 'card',
											'type'         => 'repeater',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'field_6c87ce476762d',
														'operator' => '==',
														'value'    => 'card',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'collapsed'    => '',
											'min'          => 0,
											'max'          => 0,
											'layout'       => 'block',
											'button_label' => 'Add Card',
											'sub_fields'   => array(
												array(
													'key'  => 'field_6c1bb43146a76',
													'label' => 'Image',
													'name' => 'image',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
													'preview_size' => 'medium',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => '',
												),
												array(
													'key'  => 'field_6c1bb45b46a77',
													'label' => 'Title',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key'  => 'field_6c1bb46246a78',
													'label' => 'Description',
													'name' => 'description',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'basic',
													'media_upload' => 0,
													'delay' => 1,
												),
												array(
													'key'  => 'field_6c1bb4ab46a79',
													'label' => 'Button',
													'name' => 'button',
													'type' => 'link',
													'instructions' => '',
													'required' => 1,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
												),
											),
										),
										array(
											'key'          => 'field_6c1bb70f46a7d',
											'label'        => '',
											'name'         => 'flowchart',
											'type'         => 'repeater',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'field_6c87ce476762d',
														'operator' => '==',
														'value'    => 'flowchart',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'collapsed'    => '',
											'min'          => 0,
											'max'          => 0,
											'layout'       => 'block',
											'button_label' => 'Add Flowchart Item',
											'sub_fields'   => array(
												array(
													'key'  => 'field_6c87d3849ee2c',
													'label' => 'Heading',
													'name' => 'heading_group',
													'type' => 'group',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'layout' => 'block',
													'sub_fields' => array(
														array(
															'key'  => 'field_6c87d41c9ee2e',
															'label' => 'Type',
															'name' => 'type',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'text' => 'Text',
																'logo' => 'Logo',
																'image' => 'Image',
															),
															'default_value' => array(
																0 => 'text',
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui'   => 0,
															'return_format' => 'value',
															'ajax' => 0,
															'placeholder' => '',
														),
														array(
															'key'  => 'field_6c87d4149ee2d',
															'label' => 'Text',
															'name' => 'text',
															'type' => 'text',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_6c87d41c9ee2e',
																		'operator' => '==',
																		'value' => 'text',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
														),
														array(
															'key'  => 'field_6c82bd5f5c333',
															'label' => 'Image',
															'name' => 'image',
															'type' => 'image',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_6c87d41c9ee2e',
																		'operator' => '==',
																		'value' => 'image',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'return_format' => 'array',
															'preview_size' => 'thumbnail',
															'library' => 'all',
															'min_width' => '',
															'min_height' => '',
															'min_size' => '',
															'max_width' => '',
															'max_height' => '',
															'max_size' => '',
															'mime_types' => '',
														),
														array(
															'key'  => 'field_6c87e8f47f2b8',
															'label' => 'Logo',
															'name' => 'logo',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_6c87d41c9ee2e',
																		'operator' => '==',
																		'value' => 'logo',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'agrilife' => 'AgriLife',
																'extension' => 'AgriLife Extension',
																'research' => 'AgriLife Research',
																'coals' => 'College of Agriculture & Life Sciences',
																'tvmdl' => 'TVMDL',
																'forest' => 'Forest Service',
															),
															'default_value' => array(
																0 => 'agrilife',
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui'   => 0,
															'return_format' => 'value',
															'ajax' => 0,
															'placeholder' => '',
														),
														array(
															'key'  => 'field_6c87f95ba83db',
															'label' => 'Logo Color',
															'name' => 'logo_color',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_6c87d41c9ee2e',
																		'operator' => '==',
																		'value' => 'logo',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'color' => 'Standard',
																'white' => 'White',
																'black' => 'Black',
															),
															'default_value' => array(
																0 => 'color',
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui'   => 0,
															'return_format' => 'value',
															'ajax' => 0,
															'placeholder' => '',
														),
													),
												),
												array(
													'key'  => 'field_6c8298ccc35f9',
													'label' => 'Line Color',
													'name' => 'line_color',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'none' => 'None',
														'lightgreen' => 'Light Green',
														'lightblue' => 'Light Blue',
													),
													'default_value' => array(
														0 => 'lightblue',
													),
													'allow_null' => 0,
													'multiple' => 0,
													'ui'   => 0,
													'return_format' => 'value',
													'ajax' => 0,
													'placeholder' => '',
												),
												array(
													'key'  => 'field_6c1bbbae16db1',
													'label' => 'Button',
													'name' => 'button',
													'type' => 'link',
													'instructions' => '',
													'required' => 1,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
												),
											),
										),
									),
								),
								array(
									'key'               => 'field_6c829b1dc35fa',
									'label'             => 'Arrow',
									'name'              => 'arrow_group',
									'type'              => 'group',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'layout'            => 'block',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6c8297e1c35f5',
											'label'        => 'Show',
											'name'         => 'show',
											'type'         => 'true_false',
											'instructions' => 'This option will show an arrow at the bottom of the section. It is recommended to uncheck this option for the last section on a page.',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'message'      => '',
											'default_value' => 1,
											'ui'           => 0,
											'ui_on_text'   => '',
											'ui_off_text'  => '',
										),
										array(
											'key'          => 'field_6c829b5ec35fb',
											'label'        => 'Border color',
											'name'         => 'border_color',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'field_6c8297e1c35f5',
														'operator' => '==',
														'value'    => '1',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'none' => 'None',
												'lightgreen' => 'Light Green',
												'lightblue' => 'Light Blue',
											),
											'default_value' => array(
												0 => 'lightgreen',
											),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => 'Add Section',
					'min'               => '',
					'max'               => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'service-landing-page.php',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
